### ISSUE TITLE
App directory appended to auto_registration_paths

### ISSUE THREAD

**Issue by abrthel** [rom-rb/rom-rails#75]
Question.. Is there a particular reason the app folder is joined onto the end of paths added in `auto_registration_paths`? 

_lib/rom/rails/railtie.rb:32_
```ruby
result.concat(COMPONENT_DIRS.map { |dir| root_path.join('app', dir).to_s })
```
If not, could I suggest a change where it's dropped (or another path registry is added if backwards compatibility is essential) in favor of letting the user configure their own full path. Unfortunately because of the current setup a folder structure like the one shown below isn't really possible.

```
app
  |-- persistence
       |-- commands
       |-- mappers
       |-- relations
```

As well, if a user wanted all of their persistence code in say `lib`, before it could be eager loaded you'd have to have the directory `lib\app` which seems like an odd requirement.

**Comment by cflipse** [comment]
Mostly because ROM's own loading is a bit strict, and we're trying to exclude those paths from rails' autoloading magic.

It might be possible to make this more configurable, or to push the `app` up a level (instead of autoregistering `root`, we (also?) auto-register `root/app` and let the user configure anything else.  note that this _still_ would want the stock 3 directories.

@solnic, thoughts?

**Comment by solnic** [comment]
I'm OK with any strategy that people need.

**Comment by xtagon** [comment]
I just ran into this while trying to add `rom-rails` to an existing Rails app. The app already uses `/app/commands` for its own purpose (not ROM commands) and because of that, I'm getting this error (class name edited):

```
undefined method `relation' for MyNonRomCommand:Class (NoMethodError)
```

ROM by default autoloads the commands directory and the Rails app fails to boot because it's trying to treat the classes in that directory as ROM commands without checking their type. I figured this woudl be solved by changing the autoload path, but that didn't work, because it doesn't remove the default paths.

Any ideas for solutions?

**Comment by cflipse** [comment]
Outside of moving the existing code?  Only monkeypatching the loader in rom-rails.  :/

I'll try and get a newer version of rom-rails out this week where this is more configurable.

**Comment by xtagon** [comment]
@cflipse Thanks! Moving the existing code is a suitable workaround for me. Just not ideal :)

**Comment by cflipse** [comment]
@xtagon Can you pull and test the PR in #91 ?

To use, reconfigure `config.auto_registration_paths = ["lib/persistence"]` (or wherever you're stashing your rom directories) ... this should prevent it from attempting to load from your `app/commands` directory

**Comment by xtagon** [comment]
@cflipse Thanks! It has become a lower priority for me now in the project I was testing in but I'll test it when I get a chance.

**Comment by xtagon** [comment]
@cflipse Thank you for the fix <3
