### ISSUE TITLE
Rom rb 4.0

### ISSUE THREAD

**Issue by VitaliyKovtun** [rom-rb/rom-rails#84]
Hey, how to update rom-rb to 4.0 version within this gem? Bundle installs 3.3.3 in my Gemfile.lock.

**Comment by cflipse** [comment]
currently released version already depends on rom 4.0 ... did you try `bundle update rom-rails rom` ?

Which other rom-* gems are you using?  It's possible one of them is keeping you pinned, as they havn't all had releases yet.

**Comment by VitaliyKovtun** [comment]
Thank you for your reply. =)
`bundle update rom-rails rom` installs `rom (3.3.3)` in my Gemfile.lock. Maybe, it is right?
I use
```
gem 'rom-rails'
gem 'rom-repository'
gem 'rom-sql'
```

**Comment by cflipse** [comment]
`bundle update rom rom-rails rom-sql`

longer:

This is just how Bundler works.  If you ask to update a specific gem ... it will _only_ look at upgrading the gems you ask for on the command line.  In this case, because you didn't ask to update rom-sql as well, bundler takes rom-sql 1.x dependency on rom 3.x into account, and holds the whole thing in place.

If you add a specific version request:  `gem "rom", "~> 4.0"` and then attempt to update, bundler will show you the gems preventing it from meeting that specific version request.

**Comment by VitaliyKovtun** [comment]
Oh, thanks, man.
