### ISSUE TITLE
Mapper is ignored when using custom command

### ISSUE THREAD

**Issue by firstsano** [rom-rb/rom-rails#99]
So I have `rom-http` installed, and I need to create auth. So I've created `Login` command:
```
class Login < ROM::Commands::Create[:http]
  relation :session_users
  register_as :login
  result :one

  def execute(login, password)
    response = relation
        .dataset
        .with_base_path('/customer-sessions/login')
        .with_options(request_method: :put, params: {
            login: login,
            password: password
        })
        .response
    [response]
  end
end
```
A relation:
```
class SessionUsersRelation < ROM::Relation[:http]
  gateway :volgaspot

  schema(:session_users) do
    attribute :id, Types::Strict::Int
    attribute :login, Types::Strict::String
    attribute :full_name, Types::Strict::String
  end
end
```
And a repository
```
class SessionUserRepository < ROM::Repository::Root
  root :session_users

  def login(login:, password:)
    session_users
        .map_with(:session_users_mapper)
        .command(:login)
        .call(login, password)
  end
end
```
I need to rename a couple of fields and instantiate custom model with the methods I need. For testing purposes, all I've done right now is renaming `full_name` to `name`:
```
class SessionUserMapper < ROM::Mapper
  relation :session_users

  model SessionUser

  register_as :session_users_mapper

  attribute :id
  attribute :login
  attribute :name, from: :full_name
end

```
Also here's a model with a custom method
```
class SessionUser < ROM::Struct
  constructor_type :schema

  attribute :id, Types::Strict::Int
  attribute :login, Types::Strict::String
  attribute :name, Types::Strict::String.optional

  def test
    "hello world"
  end
end
```

So what I'm expecting is that the mapper renames `full_name` to `name` and instantiates my custom model. But for some weird reason it ignores my mapper, and creates instance of ROM::Struct::SessionUser with `full_name` attribute (and of course no `test` method). And what confuses me the most is that under almost identical conditions (same relations, same mappers) _fetching_ of users does work and renames as expected.

**Comment by cflipse** [comment]
This is more of a `rom-core` thing than `rom-rails` specifically.

@solnic can correct me if I'm wrong here, but I believe that commands in general don't respect mappers.  ROM is built off the idea of command - query separation, so a `create` runs through different paths than a read.  I think there was, at one point, the though of removing the data-return (outside  of PK) for commands, but I'm not sure where that went.

If your HTTP login cycle mimicked a more standard post-and-redirect pattern, where the `login` POST returns something like an HTTP OK and a location for fetching the user, rather than expecting it to encode the results in that request, it fits better with the underlying expectations.  I understand that's less raw efficiency because two http requests, and also that you may not have any particular control over the service you're interacting with.

It's worth noting that you can call a mapper directly.  the following is not tested,  but should be something like:
```ruby
  def login(login:, password:)
    (session_users.command(:login) >> SessionUserMapper).call(login, password)
  end
```

**Comment by gotar** [comment]
if I know correctly you should use [changeset](https://rom-rb.org/4.0/learn/core/changesets/) and map data using it

**Comment by firstsano** [comment]
Thanks for response!
@cflipse At first I thought that mappers didn't load somehow and I need additional settings, but now when you've pointed out about the command - query separation I see it makes sense. Oh, and a direct mapping works like a charm, thanks!
@gotar I've used direct mapper call for now, but I'll test a changeset too. Thanks!
